In [26]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(
    "/home/ahmadian/projects/netbalance/data_repository/raw/picard/interactions.csv",
    sep=";",
    na_values="NA",
).set_index("bacteria")

In [7]:
df.head()

,55989_P2,LF82_P8,AL505_Ev3,LF73_P4,BCH953_P2,BCH953_P4,BCH953_P5,LF73_P1,LF73_P3,NIC06_P2,...,LM08_P2,NRG_12A1B,411_P1,536_P12,BDX09_P1,411_P2,LF50_P3,LM40_P1,LM40_P2,LM40_P3
bacteria,,,,,,,,,,,,,,,,,,,,,
ECOR-54,0.0,1.0,0.0,1.0,1.0,0.0,0.0,4.0,4.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIJ06,0.0,1.0,0.0,2.0,0.0,0.0,0.0,4.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ECOR-52,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ECOR-51,3.0,2.0,2.0,3.0,3.0,4.0,4.0,3.0,3.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
ECOR-55,2.0,3.0,1.0,4.0,0.0,2.0,1.0,3.0,4.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [9]:
df.shape

(402, 96)

In [17]:
bacteria = pd.DataFrame(df.index.tolist(), columns=["bacteria"])
phages = pd.DataFrame(df.columns.tolist(), columns=["phage"])
print(len(bacteria))
print(len(phages))

402
96

In [20]:
bacteria.to_csv(
    "/home/ahmadian/projects/netbalance/data_repository/processed/picard/bacteria_names.csv"
)
phages.to_csv(
    "/home/ahmadian/projects/netbalance/data_repository/processed/picard/phage_names.csv"
)

In [21]:
df.head()

,55989_P2,LF82_P8,AL505_Ev3,LF73_P4,BCH953_P2,BCH953_P4,BCH953_P5,LF73_P1,LF73_P3,NIC06_P2,...,LM08_P2,NRG_12A1B,411_P1,536_P12,BDX09_P1,411_P2,LF50_P3,LM40_P1,LM40_P2,LM40_P3
bacteria,,,,,,,,,,,,,,,,,,,,,
ECOR-54,0.0,1.0,0.0,1.0,1.0,0.0,0.0,4.0,4.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIJ06,0.0,1.0,0.0,2.0,0.0,0.0,0.0,4.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ECOR-52,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ECOR-51,3.0,2.0,2.0,3.0,3.0,4.0,4.0,3.0,3.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
ECOR-55,2.0,3.0,1.0,4.0,0.0,2.0,1.0,3.0,4.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [24]:
df = (df != 0).astype(int)

In [25]:
df.head()

,55989_P2,LF82_P8,AL505_Ev3,LF73_P4,BCH953_P2,BCH953_P4,BCH953_P5,LF73_P1,LF73_P3,NIC06_P2,...,LM08_P2,NRG_12A1B,411_P1,536_P12,BDX09_P1,411_P2,LF50_P3,LM40_P1,LM40_P2,LM40_P3
bacteria,,,,,,,,,,,,,,,,,,,,,
ECOR-54,0,1,0,1,1,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
DIJ06,0,1,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
ECOR-52,0,0,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
ECOR-51,1,1,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,1,1,0,0
ECOR-55,1,1,1,1,0,1,1,1,1,1,...,1,0,0,0,0,0,1,1,0,0

In [27]:
values = df.values
values.shape

(402, 96)

In [28]:
values[:5, :5]

array([[0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0]])

In [30]:
rows, cols = np.indices(values.shape)

In [32]:
result = pd.DataFrame(
    {
        "bacteria_idx": rows.ravel(),
        "phage_idx": cols.ravel(),
        "interaction": values.ravel(),
    }
)

# Save
result.to_csv(
    "/home/ahmadian/projects/netbalance/data_repository/processed/picard/interactions.txt",
    index=False,
    header=False,
)